package com.Younes43.GestionRessourcesHumains.Entities.Enums;

public enum BusinessUnit {
    APPLICATION_TOOLING,
    GLOBAL_AUTOMOTIVE,
    GLOBAL_FINANCE,
    GLOBAL_OPERATIONS,
    GLOBAL_TEIS,
    INDUSTRIAL,
    INDUSTRIAL_COMMERCIAL_TRANSPORTATION,
    SENSORS_SOLUTIONS,
    TE_ENERGY


    }
